version: 2

build:
  os: latest
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
  system_packages: false

sphinx:
  configuration: docs/source/conf.py

# Skip automatic docs build by using a dummy build or using plain HTML output

