version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

# Skip automatic docs build by using a dummy build or using plain HTML output

